###############################################################################
# Copyright Statement:                                                        #
#                                                                             #
#   This software/firmware and related documentation ("MediaTek Software")    #
# are protected under international and related jurisdictions'copyright laws  #
# as unpublished works. The information contained herein is confidential and  #
# proprietary to MediaTek Inc. Without the prior written permission of        #
# MediaTek Inc., any reproduction, modification, use or disclosure of         #
# MediaTek Software, and information contained herein, in whole or in part,   #
# shall be strictly prohibited.                                               #
# MediaTek Inc. Copyright (C) 2010. All rights reserved.                      #
#                                                                             #
#   BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND      #
# AGREES TO THE FOLLOWING:                                                    #
#                                                                             #
#   1)Any and all intellectual property rights (including without             #
# limitation, patent, copyright, and trade secrets) in and to this            #
# Software/firmware and related documentation ("MediaTek Software") shall     #
# remain the exclusive property of MediaTek Inc. Any and all intellectual     #
# property rights (including without limitation, patent, copyright, and       #
# trade secrets) in and to any modifications and derivatives to MediaTek      #
# Software, whoever made, shall also remain the exclusive property of         #
# MediaTek Inc.  Nothing herein shall be construed as any transfer of any     #
# title to any intellectual property right in MediaTek Software to Receiver.  #
#                                                                             #
#   2)This MediaTek Software Receiver received from MediaTek Inc. and/or its  #
# representatives is provided to Receiver on an "AS IS" basis only.           #
# MediaTek Inc. expressly disclaims all warranties, expressed or implied,     #
# including but not limited to any implied warranties of merchantability,     #
# non-infringement and fitness for a particular purpose and any warranties    #
# arising out of course of performance, course of dealing or usage of trade.  #
# MediaTek Inc. does not provide any warranty whatsoever with respect to the  #
# software of any third party which may be used by, incorporated in, or       #
# supplied with the MediaTek Software, and Receiver agrees to look only to    #
# such third parties for any warranty claim relating thereto.  Receiver       #
# expressly acknowledges that it is Receiver's sole responsibility to obtain  #
# from any third party all proper licenses contained in or delivered with     #
# MediaTek Software.  MediaTek is not responsible for any MediaTek Software   #
# releases made to Receiver's specifications or to conform to a particular    #
# standard or open forum.                                                     #
#                                                                             #
#   3)Receiver further acknowledge that Receiver may, either presently        #
# and/or in the future, instruct MediaTek Inc. to assist it in the            #
# development and the implementation, in accordance with Receiver's designs,  #
# of certain softwares relating to Receiver's product(s) (the "Services").    #
# Except as may be otherwise agreed to in writing, no warranties of any       #
# kind, whether express or implied, are given by MediaTek Inc. with respect   #
# to the Services provided, and the Services are provided on an "AS IS"       #
# basis. Receiver further acknowledges that the Services may contain errors   #
# that testing is important and it is solely responsible for fully testing    #
# the Services and/or derivatives thereof before they are used, sublicensed   #
# or distributed. Should there be any third party action brought against      #
# MediaTek Inc. arising out of or relating to the Services, Receiver agree    #
# to fully indemnify and hold MediaTek Inc. harmless.  If the parties         #
# mutually agree to enter into or continue a business relationship or other   #
# arrangement, the terms and conditions set forth herein shall remain         #
# effective and, unless explicitly stated otherwise, shall prevail in the     #
# event of a conflict in the terms in any agreements entered into between     #
# the parties.                                                                #
#                                                                             #
#   4)Receiver's sole and exclusive remedy and MediaTek Inc.'s entire and     #
# cumulative liability with respect to MediaTek Software released hereunder   #
# will be, at MediaTek Inc.'s sole discretion, to replace or revise the       #
# MediaTek Software at issue.                                                 #
#                                                                             #
#   5)The transaction contemplated hereunder shall be construed in            #
# accordance with the laws of Singapore, excluding its conflict of laws       #
# principles.  Any disputes, controversies or claims arising thereof and      #
# related thereto shall be settled via arbitration in Singapore, under the    #
# then current rules of the International Chamber of Commerce (ICC).  The     #
# arbitration shall be conducted in English. The awards of the arbitration    #
# shall be final and binding upon both parties and shall be entered and       #
# enforceable in any court of competent jurisdiction.                         #
###############################################################################
###########################################################################
# $RCSfile: Makefile,v $
# $Revision: #1 $
# $Date: 2014/12/25 $
# $Author: dtvbm11 $
#
# Description:
#         Leave-level makefile to build the subcomponent of driver library.
#
#         Specify the source files to be compile in SRC.
#############################################################################
RLS_CUSTOM_BUILD ?= false
ifeq "$(TV_DRV_VFY)" "true"
ifeq "$(TARGET_IC)" "mt5396"
	export CONFIG_MT5396_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5368"
	export CONFIG_MT5368_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5389"
	export CONFIG_MT5389_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5398"
	export CONFIG_MT5398_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5880"
	export CONFIG_MT5880_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5881"
	export CONFIG_MT5881_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5399"
	export CONFIG_MT5399_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5890"
	export CONFIG_MT5890_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5891"
	export CONFIG_MT5891_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5882"
	export CONFIG_MT5882_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5883"
	export CONFIG_MT5883_DRIVERS=m
endif
else

ifeq "$(RLS_CUSTOM_BUILD)" "true"
ifeq "$(TARGET_IC)" "mt5396"
	export CONFIG_MT5396_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5368"
	export CONFIG_MT5368_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5389"
	export CONFIG_MT5389_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5398"
	export CONFIG_MT5398_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5880"
	export CONFIG_MT5880_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5881"
	export CONFIG_MT5881_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5399"
	export CONFIG_MT5399_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5890"
	export CONFIG_MT5890_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5891"
	export CONFIG_MT5891_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5882"
	export CONFIG_MT5882_DRIVERS=m
endif
ifeq "$(TARGET_IC)" "mt5883"
	export CONFIG_MT5883_DRIVERS=m
endif
endif

endif
ifeq "$(OSAI_VER)" "2"
obj-$(CONFIG_MT5396_DRIVERS) += cb/ ioctl/ lib/ app_if/ osai_v2/
obj-$(CONFIG_MT5368_DRIVERS) += cb/ ioctl/ lib/ app_if/ osai_v2/
obj-$(CONFIG_MT5389_DRIVERS) += cb/ ioctl/ lib/ app_if/ osai_v2/
else
obj-$(CONFIG_MT5396_DRIVERS) += cb/ ioctl/ lib/ app_if/ osai/
obj-$(CONFIG_MT5368_DRIVERS) += cb/ ioctl/ lib/ app_if/ osai/
obj-$(CONFIG_MT5389_DRIVERS) += cb/ ioctl/ lib/ app_if/ osai/
endif

# For Cobra and new IC, only support OSAI V2
obj-$(CONFIG_MT5398_DRIVERS) += cb/ ioctl/ lib/ app_if/ osai_v2/
ifeq "$(TV_DRV_VFY)" "true"
ifeq "$(TARGET_IC)" "mt5880"
obj-$(CONFIG_MT5880_DRIVERS) +=  cb/ ioctl/ lib/ osai_v2/ app_if/
endif
ifeq "$(TARGET_IC)" "mt5881"
obj-$(CONFIG_MT5881_DRIVERS) +=  cb/ ioctl/ lib/ osai_v2/ app_if/
endif
ifeq "$(TARGET_IC)" "mt5890"
obj-$(CONFIG_MT5890_DRIVERS) +=  cb/ ioctl/ lib/ osai_v2/ app_if/
ifeq "$(LINUX_SLT_SUPPORT)" "true"
obj-$(CONFIG_MT5890_DRIVERS) += demo/ drv_if/
endif
endif
ifeq "$(TARGET_IC)" "mt5891"
obj-$(CONFIG_MT5891_DRIVERS) +=  cb/ ioctl/ lib/ osai_v2/ app_if/
ifeq "$(LINUX_SLT_SUPPORT)" "true"
obj-$(CONFIG_MT5891_DRIVERS) += demo/ drv_if/
endif
endif
ifeq "$(TARGET_IC)" "mt5882"
obj-$(CONFIG_MT5882_DRIVERS) +=  cb/ ioctl/ lib/ osai_v2/ app_if/
ifeq "$(LINUX_SLT_SUPPORT)" "true"
obj-$(CONFIG_MT5890_DRIVERS) += demo/ drv_if/
endif
endif
ifeq "$(TARGET_IC)" "mt5883"
obj-$(CONFIG_MT5883_DRIVERS) +=  cb/ ioctl/ lib/ osai_v2/ app_if/
endif
else
obj-$(CONFIG_MT5880_DRIVERS) += cb/ ioctl/ lib/ app_if/ osai_v2/
obj-$(CONFIG_MT5881_DRIVERS) += cb/ ioctl/ lib/ app_if/ osai_v2/
obj-$(CONFIG_MT5399_DRIVERS) += cb/ ioctl/ lib/ app_if/ osai_v2/
obj-$(CONFIG_MT5890_DRIVERS) += cb/ ioctl/ lib/ app_if/ osai_v2/
obj-$(CONFIG_MT5891_DRIVERS) += cb/ ioctl/ lib/ app_if/ osai_v2/
obj-$(CONFIG_MT5882_DRIVERS) += cb/ ioctl/ lib/ app_if/ osai_v2/
obj-$(CONFIG_MT5883_DRIVERS) += cb/ ioctl/ lib/ app_if/ osai_v2/
ifeq "$(LINUX_SLT_SUPPORT)" "true"
obj-$(CONFIG_MT5890_DRIVERS) += demo/ drv_if/
obj-$(CONFIG_MT5891_DRIVERS) += demo/ drv_if/
obj-$(CONFIG_MT5882_DRIVERS) += demo/ drv_if/
obj-$(CONFIG_MT5883_DRIVERS) += demo/ drv_if/
endif
ifneq ($(CONFIG_FB_MT53XX),)
obj-$(CONFIG_MT5396_DRIVERS) += native/
obj-$(CONFIG_MT5368_DRIVERS) += native/
obj-$(CONFIG_MT5389_DRIVERS) += native/
obj-$(CONFIG_MT5398_DRIVERS) += native/
obj-$(CONFIG_MT5880_DRIVERS) += native/
obj-$(CONFIG_MT5881_DRIVERS) += native/
obj-$(CONFIG_MT5399_DRIVERS) += native/
obj-$(CONFIG_MT5890_DRIVERS) += native/
obj-$(CONFIG_MT5891_DRIVERS) += native/
obj-$(CONFIG_MT5882_DRIVERS) += native/
obj-$(CONFIG_MT5883_DRIVERS) += native/
endif
endif

