/*#########################################################

                         BRANCHES.H                        

Do Not Modify!!! This file is auto generated by branches.mk
#########################################################*/
#ifndef	_branches_h_
#define	_branches_h_

#ifdef __cplusplus
extern "C" {
#endif

#define	_SYS_ATSC		10000
#define	_SYS_DVB		20000
#define	_SYS_DVB_TW		21000
#define	_SYS_ISDB		30000
#define	_SYS_UNKNOWN	50000

#define	SYS_ATSC	((_SYS_ATSC		<= _SYS_TYPE_) && (_SYS_TYPE_ < _SYS_DVB))
#define	SYS_DVB		((_SYS_DVB		<= _SYS_TYPE_) && (_SYS_TYPE_ < _SYS_ISDB))
#define	SYS_DVB_TW	((_SYS_DVB_TW	== _SYS_TYPE_))
#define	SYS_ISDB	((_SYS_ISDB		<= _SYS_TYPE_) && (_SYS_TYPE_ < _SYS_UNKNOWN))
#define	SYS_UNKNOWN	(_SYS_UNKNOWN	<= _SYS_TYPE_)

#ifdef __cplusplus
}
#endif

#endif	/* _branches_h_ */
